version: '3.8'
networks:
  nginx-proxy:
    external:
      name: reverse-proxy
  back:
    driver: bridge
services:
  app:
    build: .
    container_name: QZvision
    restart: always
    networks:
      - nginx-proxy
      - back
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase

  db:
    image: postgres:14
    networks:
      - back
    container_name: qazvision-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ahan2004
      POSTGRES_DB: main
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    container_name: qazvision-nginx-proxy
    networks:
      - nginx-proxy
    volumes:
      - ./../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./../ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
