version: '3.8'

services:
  app:
    build: .
    container_name: QZvision
    restart: always

  nginx:
    image: nginx:latest
    container_name: qazvision-nginx-proxy
    volumes:
      - ./../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./../ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app


